maruku:
  use_tex:    true
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex/
pygments: true
permalink:      /:categories/:title/

title:          Alexander Vinokurov homepage
url:            http://alexander-vinokurov.com


nav:
    - name:     Blog
      url:      /blog/

    - name:     Resume
      url:      /resume/


