maruku:
  use_tex:    true
  use_divs:   false
pygments: true
permalink:      /:categories/:title/

title:          Alexander Vinokurov
url:            http://alexander-vinokurov.com


nav:
    - name:     Blog
      url:      /blog/

    - name:     Resume
      url:      /resume/

    - name:     Publications
      url:      /publications/

    - name:     Research
      url:      /research/

authors: {
     vinokurov: {
         name:    Alexander Vinokurov,
         url:     http://alexander-vinokurov.com,
         email:   alexander.a.vinokurov@gmail.com
     }
}
